import type { Property, SimilarProperty } from "@/lib/types/property";

export const sampleProperty: Property = {
  id: "chpk1487075",
  title: "6 Bedroom House",
  address: "Bourne Street, Belgravia, London SW1W",
  postcode: "SW1W 8JW",
  price: "£15,500,000",
  priceValue: 15500000,
  priceQualifier: "Guide Price",
  status: "for_sale",
  type: "Terraced House",
  featured: true,
  newListing: true,
  addedDate: "2024-02-26",
  beds: 6,
  baths: 4,
  receptions: 3,
  sqft: 5759,
  sqm: 535.01,
  description: `This impressive 6 bedroom townhouse within a development which completed circa 2001, benefits from an impressive private swimming pool, steam room, lift access, private sunny garden and large underground garage.

The property is arranged over five floors and includes an elegant entrance hall, grand double reception room, open-plan kitchen and family room with bi-fold doors opening onto a west-facing garden. The master suite occupies the entire second floor with dressing room and en-suite bathroom.

Additional features include air conditioning, underfloor heating, integrated Sonos sound system, and a separate utility room.

The location is superb, situated in the heart of Belgravia, moments from the boutiques and restaurants of Motcomb Street and Sloane Street. Victoria Station is within easy walking distance providing excellent transport links.

The property is offered chain free and early viewing is highly recommended to appreciate the quality and scale of accommodation on offer.`,
  features: [
    "Private swimming pool",
    "Steam room",
    "Lift access to all floors",
    "Private west-facing garden",
    "Large underground garage",
    "Air conditioning",
    "Underfloor heating",
    "Integrated Sonos sound system",
    "Bi-fold doors to garden",
    "Master suite with dressing room",
    "Chain free",
    "24-hour concierge",
  ],
  images: [
    {
      id: "img-1",
      url: "/hertfordshire-home-1.png",
      alt: "Front exterior view of the property",
      isPrimary: true,
      caption: "Main entrance",
    },
    {
      id: "img-2",
      url: "/hertfordshire-home-4.png",
      alt: "Rear garden view",
      isPrimary: false,
      caption: "Private garden",
    },
    {
      id: "img-3",
      url: "/hertfordshire-home-1.png",
      alt: "Swimming pool",
      isPrimary: false,
      caption: "Swimming pool",
    },
    {
      id: "img-4",
      url: "/hertfordshire-home-4.png",
      alt: "Kitchen and family room",
      isPrimary: false,
      caption: "Kitchen/Family room",
    },
    {
      id: "img-5",
      url: "/hertfordshire-home-1.png",
      alt: "Master bedroom",
      isPrimary: false,
      caption: "Master bedroom",
    },
    {
      id: "img-6",
      url: "/hertfordshire-home-4.png",
      alt: "Reception room",
      isPrimary: false,
      caption: "Reception room",
    },
    {
      id: "img-7",
      url: "/hertfordshire-home-1.png",
      alt: "Bathroom",
      isPrimary: false,
      caption: "En-suite bathroom",
    },
    {
      id: "img-8",
      url: "/hertfordshire-home-4.png",
      alt: "Garden terrace",
      isPrimary: false,
      caption: "Garden terrace",
    },
    {
      id: "img-9",
      url: "/hertfordshire-home-1.png",
      alt: "Underground garage",
      isPrimary: false,
      caption: "Garage",
    },
    {
      id: "img-10",
      url: "/hertfordshire-home-4.png",
      alt: "Lift interior",
      isPrimary: false,
      caption: "Private lift",
    },
    {
      id: "img-11",
      url: "/hertfordshire-home-1.png",
      alt: "Steam room",
      isPrimary: false,
      caption: "Steam room",
    },
    {
      id: "img-12",
      url: "/hertfordshire-home-4.png",
      alt: "Guest bedroom",
      isPrimary: false,
      caption: "Guest bedroom",
    },
  ],
  virtualTour: {
    provider: "matterport",
    url: "https://my.matterport.com/show/?m=example",
    thumbnail: "/hertfordshire-home-1.png",
  },
  floorplans: [
    {
      id: "fp-1",
      url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1600&q=80",
      title: "Ground Floor",
      dimensions: { width: 45, height: 32, unit: "ft" },
      rooms: [
        { name: "Entrance Hall", dimensions: "12'6\" x 8'2\"", area: 102 },
        { name: "Kitchen/Family", dimensions: "24' x 18'6\"", area: 444 },
        { name: "Utility", dimensions: "8' x 6'", area: 48 },
        { name: "WC", dimensions: "5' x 4'", area: 20 },
      ],
    },
    {
      id: "fp-2",
      url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1600&q=80",
      title: "First Floor",
      dimensions: { width: 45, height: 32, unit: "ft" },
      rooms: [
        { name: "Reception Room", dimensions: "28' x 20'", area: 560 },
        { name: "Dining Room", dimensions: "16' x 14'", area: 224 },
        { name: "Study", dimensions: "10' x 8'", area: 80 },
      ],
    },
    {
      id: "fp-3",
      url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1600&q=80",
      title: "Second Floor (Master Suite)",
      dimensions: { width: 45, height: 32, unit: "ft" },
      rooms: [
        { name: "Master Bedroom", dimensions: "26' x 18'", area: 468 },
        { name: "Dressing Room", dimensions: "12' x 10'", area: 120 },
        { name: "En-suite", dimensions: "14' x 8'", area: 112 },
      ],
    },
    {
      id: "fp-4",
      url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1600&q=80",
      title: "Lower Ground Floor",
      dimensions: { width: 45, height: 32, unit: "ft" },
      rooms: [
        { name: "Swimming Pool", dimensions: "32' x 16'", area: 512 },
        { name: "Steam Room", dimensions: "8' x 6'", area: 48 },
        { name: "Garage", dimensions: "24' x 20'", area: 480 },
        { name: "Storage", dimensions: "12' x 8'", area: 96 },
      ],
    },
  ],
  epc: {
    currentRating: "C",
    potentialRating: "B",
    currentScore: 72,
    potentialScore: 84,
    validUntil: "2029-12-25",
    certificateUrl: "#",
    estimatedCosts: {
      heating: "£1,800",
      lighting: "£450",
      hotWater: "£350",
      total: "£2,600",
    },
    potentialCosts: {
      heating: "£1,200",
      lighting: "£300",
      hotWater: "£250",
      total: "£1,750",
    },
    improvements: [
      {
        description: "Increase loft insulation to 270mm",
        cost: "£100 - £350",
        annualSavings: "£120",
        ratingImprovement: "C → B",
      },
      {
        description: "Low energy lighting for all fixed outlets",
        cost: "£70",
        annualSavings: "£50",
        ratingImprovement: "No change",
      },
      {
        description: "Solar photovoltaic panels, 2.5 kWp",
        cost: "£3,500 - £5,500",
        annualSavings: "£380",
        ratingImprovement: "C → B",
      },
    ],
  },
  mapCoordinates: {
    lat: 51.4988,
    lng: -0.1491,
  },
  streetView: {
    heading: 180,
    pitch: 0,
    zoom: 1,
  },
  transport: [
    {
      id: "st-1",
      name: "Victoria",
      type: "tube",
      distance: "0.3 miles",
      walkingTime: 6,
      drivingTime: 2,
      lines: ["District", "Circle", "Victoria"],
      zone: 1,
      coordinates: { lat: 51.4965, lng: -0.1441 },
    },
    {
      id: "st-2",
      name: "Sloane Square",
      type: "tube",
      distance: "0.4 miles",
      walkingTime: 8,
      drivingTime: 3,
      lines: ["District", "Circle"],
      zone: 1,
      coordinates: { lat: 51.4923, lng: -0.1565 },
    },
    {
      id: "st-3",
      name: "Hyde Park Corner",
      type: "tube",
      distance: "0.6 miles",
      walkingTime: 12,
      drivingTime: 4,
      lines: ["Piccadilly"],
      zone: 1,
      coordinates: { lat: 51.5027, lng: -0.1527 },
    },
    {
      id: "st-4",
      name: "London Victoria",
      type: "rail",
      distance: "0.4 miles",
      walkingTime: 8,
      drivingTime: 3,
      lines: ["Gatwick Express", "Southeastern", "Southern"],
      zone: 1,
      coordinates: { lat: 51.4952, lng: -0.1439 },
    },
  ],
  amenities: [
    {
      id: "am-1",
      name: "The Thomas's Battersea",
      type: "school",
      distance: "0.2 miles",
      walkingTime: 4,
      rating: 4.8,
      address: "4-5 The Courtyard, Cottesmore Gardens",
    },
    {
      id: "am-2",
      name: "Waitrose & Partners",
      type: "supermarket",
      distance: "0.2 miles",
      walkingTime: 4,
      rating: 4.5,
      address: "117-125 Motcomb St",
    },
    {
      id: "am-3",
      name: "The Alfred Tennyson",
      type: "pub",
      distance: "0.1 miles",
      walkingTime: 2,
      rating: 4.4,
      address: "10 Motcomb St",
    },
    {
      id: "am-4",
      name: "Eaton Square Gardens",
      type: "park",
      distance: "0.3 miles",
      walkingTime: 6,
      rating: 4.7,
      address: "Eaton Square",
    },
    {
      id: "am-5",
      name: "Ossiano",
      type: "restaurant",
      distance: "0.2 miles",
      walkingTime: 4,
      rating: 4.6,
      address: "34-55 Motcomb St",
    },
    {
      id: "am-6",
      name: "Third Space",
      type: "gym",
      distance: "0.4 miles",
      walkingTime: 8,
      rating: 4.5,
      address: "67 Brewer St",
    },
    {
      id: "am-7",
      name: "Chelsea & Westminster Hospital",
      type: "hospital",
      distance: "1.2 miles",
      walkingTime: 24,
      rating: 4.2,
      address: "369 Fulham Rd",
    },
    {
      id: "am-8",
      name: "Boots Pharmacy",
      type: "pharmacy",
      distance: "0.3 miles",
      walkingTime: 6,
      rating: 4.0,
      address: "120 Victoria St",
    },
  ],
  walkScore: {
    score: 98,
    description: "Walker's Paradise",
    transitScore: 100,
    bikeScore: 85,
  },
  tenure: {
    type: "Leasehold plus share of freehold",
    leaseExpires: "25 December 2999",
    serviceCharge: "£10,000 per quarter (2025)",
    councilTax: "£2,034.36 per year (Band H)",
    localAuthority: "City of Westminster",
  },
  agent: {
    id: "agent-1",
    name: "James Harrington",
    title: "Senior Property Consultant",
    phone: "020 7123 4567",
    mobile: "07700 900123",
    email: "james.harrington@banc.co.uk",
    image: "/banc-logo.png",
    branch: {
      name: "Banc Belgravia",
      address: "15 Motcomb Street, London SW1X 8LB",
      phone: "020 7123 4567",
      openingHours: "Mon-Fri 9am-6pm, Sat 10am-4pm",
    },
  },
  history: [
    {
      date: "2024-02-26",
      event: "listed",
      price: "£15,500,000",
      agent: "Banc Belgravia",
    },
    {
      date: "2021-08-15",
      event: "sold",
      price: "£12,750,000",
      priceChange: "+21.6%",
    },
    {
      date: "2016-03-20",
      event: "sold",
      price: "£8,200,000",
      priceChange: "+55.5%",
    },
    {
      date: "2008-11-12",
      event: "sold",
      price: "£5,275,000",
      agent: "Previous Agent",
    },
  ],
  reference: "CHPK1487075",
};

export const similarProperties: SimilarProperty[] = [
  {
    id: "chpk1487076",
    title: "5 Bedroom House",
    address: "Eaton Square, Belgravia, London SW1W",
    price: "£12,950,000",
    beds: 5,
    baths: 3,
    sqft: 4850,
    image: "/hertfordshire-home-1.png",
  },
  {
    id: "chpk1487077",
    title: "4 Bedroom Penthouse",
    address: "Wilton Crescent, Belgravia, London SW1X",
    price: "£8,500,000",
    beds: 4,
    baths: 3,
    sqft: 3200,
    image: "/hertfordshire-home-4.png",
  },
  {
    id: "chpk1487078",
    title: "6 Bedroom House",
    address: "Lyall Street, Belgravia, London SW1X",
    price: "£18,750,000",
    beds: 6,
    baths: 5,
    sqft: 7200,
    image: "/hertfordshire-home-1.png",
  },
];
